name: neuro_gym
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  supabase_flutter: ^2.5.0
  cupertino_icons: ^1.0.6
  http: ^1.6.0
  fl_chart: ^0.68.0
  flutter_markdown: ^0.7.7+1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
